# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_comment',
            new_name='is_approved',
        ),
    ]
